password = "12345"
OPENAI_API_KEY = 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