password = "12345"
OPENAI_API_KEY = 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