password = "12345"
OPENAI_API_KEY = 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